### ISSUE TITLE
Update readme about how to get started

### ISSUE THREAD

**Issue by eboody** [nitn3lav/derived-cms#35]
I'd love to give this a whirl but the example isn't compiling for me :/

**Comment by boris-schwarz** [comment]
Got it running by doing following

1. Add following dependencies to `cargo.toml`

```toml
[dependencies]
axum = "0.8.8"
chrono = "0.4.42"
derived-cms = {version="0.6.1", features=["sqlite", "json"]}
ormlite = {version="0.23.3", features=["sqlite"]}
serde = "1.0.228"
sqlx = {version="0.8.6", features=["runtime-tokio", "tls-rustls-ring-webpki"]}
tokio = "1.49.0"
ts-rs = "10.1.0"
uuid = {version="1.19.0", features=["v4"]}

```

2. Add following code to `main.rs`

```rust
#[derive(Debug, Clone, Serialize)]
struct MyError;

impl fmt::Display for MyError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "An error occured")
    }
}
impl std::error::Error for MyError {}
impl From<MyError> for AppError {
    fn from(_: MyError) -> Self {
        AppError::new("Error".to_owned(), "An error occured".to_owned())
    }
}
impl From<ormlite::Error> for MyError {
    fn from(_: ormlite::Error) -> Self {
        MyError
    }
}

impl From<sqlx::Error> for MyError {
    fn from(_: sqlx::Error) -> Self {
        MyError
    }
}
```

3. Create `/.tmp/db.sqlite`

The code will compile, but firing a GET request to http://127.0.0.1:3000/api/v1/posts returns a 400 Bad Request and firing a POST request to http://127.0.0.1:3000/api/v1/posts with following body returns a 400 Bad Request too:
```json
{
  "title": "foo",
  "date": "2026-01-07T10:30:00Z",
  "body": ["text"],
  "draft": false
}
```
For now, I will not look into it any further, but maybe that helps you. 

Cheers, Boris
